### ISSUE TITLE
Installation dependencies are incomplete

### ISSUE THREAD

**Issue by mileslucas** [hpparvi/PyTransit#117]
https://github.com/hpparvi/PyTransit/blob/826ce3a53fc820a3fe24f812dc0c4dc3208a946b/setup.py#L34

`pyrr` and `seaborn` are not in the dependency list, but basic importing doesn't work without having them installed
```
$ pip install pytransit
```
```python
>>> import pytransit
[...]
~/dev/yeehaw/.venv/lib/python3.7/site-packages/pytransit/utils/octasphere.py in <module>
     22 from math import sin, cos, acos, pi
     23 from numpy import empty, array, vstack, cross, dot
---> 24 from pyrr import quaternion
     25 
     26 
ModuleNotFoundError: No module named 'pyrr'
```
and similar for `seaborn`

After manually installing `pyrr` and `seaborn` import works fine.

**Comment by hpparvi** [comment]
Thanks for pointing this out, @mileslucas. Should be fixed now.
