### ISSUE TITLE
Stellar oblateness computation

### ISSUE THREAD

**Issue by delinea** [hpparvi/PyTransit#135]
The computation of the stellar oblateness _f_ in _pytransit/models/numba/gdmodel.py_ assumes a density computed from a spherical star:
`rho = M_star * (4/3 * pi * R_star**3)`
to simplify the original expression of _f_:
`f = w**2 * R_star**3 / (2 * G * M_star)`

One can however include the stellar oblateness in the expression of the density:
`rho = M_star * (4/3 * pi * R_star**3 * (1-f))`
and then solve the resulting quadratic equation in _f_ that gives a single possible value:
**`f = 0.5 * (1 - sqrt(1 - 3.*w*w / (2.*G*pi*rho)))`**
that should be returned by the `stellar_oblateness(w, rho)` function.

Of course, for slow rotators, `w << 1` => `f ~ 3.*w*w/(8.*G*pi*rho)`, which is the current implementation.

**Comment by hpparvi** [comment]
Changed as suggested!

**Comment by delinea** [comment]
**Erratum:**
I recomputed the stellar oblateness from scratch instead of the reference formula `f = w**2 * R_star**3 / (2 * G * M_star)` and I found:
`f = 1 / (1 + (2 * G * M_star) / (w**2 * R_star**3))`

Injecting the density of an oblate star
`rho = M_star * (4/3 * pi * R_star**3 * (1-f))`
into the correct expression of *f* leads to
`f = 3*w**2 / (8 * G * pi * rho)`, which was the expression implemented initially...

Apologies for the erroneous suggestion I made earlier.

**Comment by hpparvi** [comment]
Thanks for double-checking this, I've reverted the function back to the original.
