### ISSUE TITLE
fatal error 1181

### ISSUE THREAD

**Issue by linobellone** [hpparvi/PyTransit#19]
Lino Bellone
Sorry to disturb you, but I'm not an experienced user: trying to install pytransit, I received this error:

...........
...........
Found executable C:\Users\edoar\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe
C:\Users\edoar\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DDCHUNK_SIZE=128 -Ibuild\src.win-amd64-2.7 -IC:\Users\edoar\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\edoar\Anaconda2\include -IC:\Users\edoar\Anaconda2\PC /Tcbuild\src.win-amd64-2.7\fortranobject.c /Fobuild\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\fortranobject.obj
compiling Fortran 90 module sources
Fortran f77 compiler: C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\gfortran.exe -Wall -g -ffixed-form -fno-second-underscore -Ofast
Fortran f90 compiler: C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\gfortran.exe -cpp -fopenmp -march=native -Ofast
Fortran fix compiler: C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\gfortran.exe -Wall -g -ffixed-form -fno-second-underscore -cpp -fopenmp -march=native -Ofast
compile options: '-DDCHUNK_SIZE=128 -Ibuild\src.win-amd64-2.7 -IC:\Users\edoar\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\edoar\Anaconda2\include -IC:\Users\edoar\Anaconda2\PC -c'
extra options: '-Jbuild\temp.win-amd64-2.7\Release\pytransit -Ibuild\temp.win-amd64-2.7\Release\pytransit'
gfortran.exe:f90: src/gimenez.f90
compiling Fortran sources
Fortran f77 compiler: C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\gfortran.exe -Wall -g -ffixed-form -fno-second-underscore -Ofast
Fortran f90 compiler: C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\gfortran.exe -cpp -fopenmp -march=native -Ofast
Fortran fix compiler: C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\gfortran.exe -Wall -g -ffixed-form -fno-second-underscore -cpp -fopenmp -march=native -Ofast
compile options: '-DDCHUNK_SIZE=128 -Ibuild\src.win-amd64-2.7 -IC:\Users\edoar\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\edoar\Anaconda2\include -IC:\Users\edoar\Anaconda2\PC -c'
extra options: '-Jbuild\temp.win-amd64-2.7\Release\pytransit -Ibuild\temp.win-amd64-2.7\Release\pytransit'
gfortran.exe:f90: build\src.win-amd64-2.7\pytransit\gimenez_f-f2pywrappers2.f90
could not find library 'gomp' in directories []
could not find library 'm' in directories []
C:\Users\edoar\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:"C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\lib\gcc\i686-w64-mingw32\6.3.0" /LIBPATH:C:\Users\edoar\Anaconda2\libs /LIBPATH:C:\Users\edoar\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\edoar\Anaconda2\PC\VS9.0\amd64 /LIBPATH:C:\Users\edoar\Anaconda2\libs /LIBPATH:C:\Users\edoar\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\edoar\Anaconda2\PC\VS9.0\amd64 gomp.lib m.lib /EXPORT:initgimenez_f build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pytransit\gimenez_fmodule.obj build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\fortranobject.obj build\temp.win-amd64-2.7\Release\src\gimenez.o build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pytransit\gimenez_f-f2pywrappers2.o /OUT:build\lib.win-amd64-2.7\pytransit\gimenez_f.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pytransit\gimenez_f.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pytransit\gimenez_f.pyd.manifest
Found executable C:\Users\edoar\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe
LINK : fatal error LNK1181: cannot open input file 'gomp.lib'
error: Command "C:\Users\edoar\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:"C:\Program Files (x86)\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\lib\gcc\i686-w64-mingw32\6.3.0" /LIBPATH:C:\Users\edoar\Anaconda2\libs /LIBPATH:C:\Users\edoar\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\edoar\Anaconda2\PC\VS9.0\amd64 /LIBPATH:C:\Users\edoar\Anaconda2\libs /LIBPATH:C:\Users\edoar\Anaconda2\PCbuild\amd64 /LIBPATH:C:\Users\edoar\Anaconda2\PC\VS9.0\amd64 gomp.lib m.lib /EXPORT:initgimenez_f build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pytransit\gimenez_fmodule.obj build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\fortranobject.obj build\temp.win-amd64-2.7\Release\src\gimenez.o build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pytransit\gimenez_f-f2pywrappers2.o /OUT:build\lib.win-amd64-2.7\pytransit\gimenez_f.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pytransit\gimenez_f.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\build\src.win-amd64-2.7\pytransit\gimenez_f.pyd.manifest" failed with exit status 1181

**Comment by hpparvi** [comment]
Hi Lino,

Sorry, I've never tried compiling PyTransit in Windows :/ The linker cannot find the gomp and m libraries, so you may need to check your paths. Have you compiled Fortran code successfully before with your current setup?

**Comment by linobellone** [comment]
Thank you for the replay,
No the fortran compiler is just installed but I tried to find in all disk the libs gomp and m but there are not!
Every suggestion will be appreciated.
Many thanks and best regards,
Lino

Inviato da iPhone
