### ISSUE TITLE
installation error in  fedora

### ISSUE THREAD

**Issue by krsreenivas95** [hpparvi/PyTransit#29]
Hi...I'am using Fedora 28 and facing with this problem ..note that I'am using Python 3.6....Don't know what to do....
Error: Symbol ‘chunk_size’ at (1) has no IMPLICIT type
error: Command "/usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops -DDCHUNK_SIZE=128 -Ibuild/src.linux-x86_64-3.6/build/src.linux-x86_64-3.6/pytransit -I/home/sreenivas/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c -c src/gimenez.f90 -o build/temp.linux-x86_64-3.6/src/gimenez.o -Jbuild/temp.linux-x86_64-3.6/pytransit -Ibuild/temp.linux-x86_64-3.6/pytransit" failed with exit status 1

**Comment by hpparvi** [comment]
Hi,

Sorry for taking so long... Other people have had the same problem, which can be fixed by including the `-cpp` flag into `f90flags` as explained now in #30. 

Cheers,
Hannu
