### ISSUE TITLE
new version breaks k2ps

### ISSUE THREAD

**Issue by benjaminpope** [hpparvi/PyTransit#31]
Hi Hannu,

Since I upgraded pytransit I have problems with k2ps:

---> 22 from k2ps.psearch import TransitSearch
     23 from scipy.ndimage import binary_dilation
     24 from pytransit import MandelAgol as MA

~/.local/lib/python3.7/site-packages/k2ps/psearch.py in <module>()
     21 from scipy.optimize import minimize
     22 
---> 23 from pytransit.orbits_f import orbits as of
     24 from exotk.utils.orbits import as_from_rhop, i_from_baew
     25 from exotk.utils.misc_f import utilities as uf

ModuleNotFoundError: No module named 'pytransit.orbits_f'

**Comment by hpparvi** [comment]
Fixed by developing k2ps into OpenTS ;)
