### ISSUE TITLE
Segmentation fault (core dumped) was happened, when I import pytransit with import george.

### ISSUE THREAD

**Issue by TakuNishiumi** [hpparvi/PyTransit#38]
Hi, Hannu.

**Describe the bug**
When I import pytransit and george at the same time, I got this problem.
I confirmed it in 2 environments(I mean two PCs).
If you know how to solve this, Could you teach us?

```
(py3) muscat@muscat-ut ~ $ ipython
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pytransit                                           
In [2]: import george                                              
Segmentation fault (core dumped)
```
also, 
```
(py3) muscat@muscat-ut ~ $ ipython
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import george                                              
In [2]: import pytransit                                           
Segmentation fault (core dumped)
```

**To Reproduce**
1. `import george` or `import pytransit`
2. `import pytransit` or `import george`
3. It shows `Segmentation fault (core dumped)`

**Desktop:**
PC1 (work station, almost all muscat Japanese member uses for analysis)
 - OS: Linux Mint 18.3 Sylvia (GNU/Linux 4.10.0-38-generic x86_64)
 - Version :Python 3.6.3 |Anaconda, Inc.|

PC2 (general PC)
- OS: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-55-generic x86_64)
- Version :conda, python version : 3.7.3.final.0

Sincerely,
Taku

**Comment by hpparvi** [comment]
Hi Taku,

Is this issue still occurring?

Cheers,
Hannu

**Comment by TakuNishiumi** [comment]
Thank you, Hannu.
I checked now, it was solved.
I don't know why...

Anyway, Thank you.
