### ISSUE TITLE
CeleriteLogLikelihood requires celerite.

### ISSUE THREAD

**Issue by MohammadEftekhar** [hpparvi/PyTransit#39]
In the PyTransit/notebooks/tess_examples/WASP-4b.ipynb:
 lpf = TESSLPF('WASP-4b', dfile, zero_epoch=zero_epoch.n, period=period.n, nsamples=2, bldur=0.25) 

Gives error: ImportError                               Traceback (most recent call last)
<ipython-input-46-066e4ece1c79> in <module>
----> 1 lpf = TESSLPF('WASP-4b', dfile, zero_epoch=zero_epoch.n, period=period.n, nsamples=2, bldur=0.25)
      2 
      3 tn = int(round((lpf.times[0].mean() - lpf.zero_epoch) / period.n))
      4 tc = zero_epoch + tn*period
      5 

~/.local/lib/python3.6/site-packages/pytransit/lpf/tesslpf.py in __init__(self, name, dfile, tic, zero_epoch, period, nsamples, trdur, bldur, use_pdc, split_transits, separate_noise, tm, minpt)
    139         wnids = arange(len(times)) if separate_noise else None
    140         BaseLPF.__init__(self, name, ['TESS'], times=times, fluxes=fluxes, pbids=pbids,
--> 141                          nsamples=nsamples, exptimes=[0.00139], wnids=wnids, tref=tref, tm=tm)
    142 
    143     def _init_lnlikelihood(self):

~/.local/lib/python3.6/site-packages/pytransit/lpf/lpf.py in __init__(self, name, passbands, times, fluxes, errors, pbids, covariates, wnids, tm, nsamples, exptimes, init_data, result_dir, tref, lnlikelihood)
    210             self._init_instrument()
    211 
--> 212         self._init_lnlikelihood()
    213         self._init_baseline()
    214         self._post_initialisation()

~/.local/lib/python3.6/site-packages/pytransit/lpf/tesslpf.py in _init_lnlikelihood(self)
    142 
    143     def _init_lnlikelihood(self):
--> 144         self._add_lnlikelihood_model(CeleriteLogLikelihood(self))
    145 
    146     def add_ldtk_prior(teff, logg, z):

~/.local/lib/python3.6/site-packages/pytransit/lpf/loglikelihood/celeriteloglikelihood.py in __init__(self, lpf, name, noise_ids, fixed_hps)
     30     def __init__(self, lpf, name: str = 'gp', noise_ids=None, fixed_hps=None):
     31         if not with_celerite:
---> 32             raise ImportError("CeleriteLogLikelihood requires celerite.")
     33 
     34         self.name = name

ImportError: CeleriteLogLikelihood requires celerite.

**Comment by hpparvi** [comment]
Hi Mohammad,

PyTransit includes only the packages required for the transit models into the requirements, and packages such as celerite need to be installed separately if you're using CeleriteLogLikelihood. So, you can fix this by installing celerite using either pip or conda (or cloning it from the GitHub repo), after which everything should be ok.

Cheers,
Hannu
