### ISSUE TITLE
Installation issue - import error

### ISSUE THREAD

**Issue by simonehagey** [hpparvi/PyTransit#61]
**Describe the bug**
When trying to pip install there seems to be an import error. It says ImportError: No module named semantic_version. I tried gitclone and running python setup.py and the same issue occurred. 

**Error received**

    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/20/17pdj9qj2v71hjsr1g7pstgw0000gn/T/pip-install-0pz7tO/pytransit/setup.py'"'"'; __file__='"'"'/private/var/folders/20/17pdj9qj2v71hjsr1g7pstgw0000gn/T/pip-install-0pz7tO/pytransit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/20/17pdj9qj2v71hjsr1g7pstgw0000gn/T/pip-pip-egg-info-vtk4uz
         cwd: /private/var/folders/20/17pdj9qj2v71hjsr1g7pstgw0000gn/T/pip-install-0pz7tO/pytransit/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/20/17pdj9qj2v71hjsr1g7pstgw0000gn/T/pip-install-0pz7tO/pytransit/setup.py", line 21, in <module>
        exec(fp.read(), version)
      File "<string>", line 17, in <module>
    ImportError: No module named semantic_version
    ----------------------------------------

**Comment by simonehagey** [comment]
Sorry, I figured it out!

**Comment by hpparvi** [comment]
Hi Simone,

Sorry for the delay, and great that you got it working! Can you still let me know what was finally the problem? 

Cheers,
Hannu

**Comment by simonehagey** [comment]
Hi Hannu,

Thanks for getting back to me! It was a really silly issue on my part. I didn’t realize that semantic_version was an external python module that I had to install first, so I was getting an error because I didn’t have it installed. I’m kind of new to this sort of stuff, so I didn’t recognize that the error was on my end. I’m excited to start working with it, now. Sorry to bother you!

Cheers,
Simone



On Nov 16, 2020, at 3:43 AM, Hannu Parviainen <notifications@github.com> wrote:

﻿

Hi Simone,

Sorry for the delay, and great that you got it working! Can you still let me know what was finally the problem?

Cheers,
Hannu
