### ISSUE TITLE
utils.f90 missing

### ISSUE THREAD

**Issue by geoffgrimwood** [hpparvi/PyTransit#7]
Macintosh:PyTransit geoff$ setup.py config_fc --fcompiler=gnu95 --opt="-Ofast" --f90flags="-cpp -fopenmp -march=native" build

[snip]

building extension "pytransit.utils_f" sources
f2py options: []
f2py:> build/src.macosx-10.10-x86_64-2.7/pytransit/utils_fmodule.c
IOError: [Errno 2] No such file or directory: 'src/utils.f90'. Skipping file "src/utils.f90".
Reading fortran codes...
Post-processing...
Post-processing (stage 2)...
Building modules...
error: f2py target file 'build/src.macosx-10.10-x86_64-2.7/pytransit/utils_fmodule.c' not generated

**Comment by hpparvi** [comment]
Fixed, thanks for the heads up.
