### ISSUE TITLE
test_gimenez.py TypeError: __init__() got an unexpected keyword argument 'lerp'

### ISSUE THREAD

**Issue by geoffgrimwood** [hpparvi/PyTransit#9]
Also applies to test_ma.py with call to MandelAgol

Macintosh:tests geoff$ python test_gimenez.py 
EEEEEE
======================================================================
ERROR: test_lerp_basic (__main__.TestGimenezModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gimenez.py", line 33, in test_lerp_basic
    f = Gimenez(npol=500, nthr=1, lerp=True)(self.z, self.k, self.u[0])
TypeError: __init__() got an unexpected keyword argument 'lerp'

======================================================================
ERROR: test_lerp_npol (__main__.TestGimenezModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gimenez.py", line 49, in test_lerp_npol
    f = Gimenez(npol=100, nthr=1, lerp=True)(self.z, self.k, self.u[0])
TypeError: __init__() got an unexpected keyword argument 'lerp'

======================================================================
ERROR: test_lerp_threading (__main__.TestGimenezModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gimenez.py", line 67, in test_lerp_threading
    f = Gimenez(npol=500, nthr=nthr, lerp=True)(self.z, self.k, self.u[0])
TypeError: __init__() got an unexpected keyword argument 'lerp'

======================================================================
ERROR: test_nolerp_basic (__main__.TestGimenezModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gimenez.py", line 25, in test_nolerp_basic
    f = Gimenez(npol=500, nthr=1, lerp=False)(self.z, self.k, self.u[0])
TypeError: __init__() got an unexpected keyword argument 'lerp'

======================================================================
ERROR: test_nolerp_npol (__main__.TestGimenezModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gimenez.py", line 41, in test_nolerp_npol
    f = Gimenez(npol=100, nthr=1, lerp=False)(self.z, self.k, self.u[0])
TypeError: __init__() got an unexpected keyword argument 'lerp'

======================================================================
ERROR: test_nolerp_threading (__main__.TestGimenezModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gimenez.py", line 58, in test_nolerp_threading
    f = Gimenez(npol=500, nthr=nthr, lerp=False)(self.z, self.k, self.u[0])
TypeError: __init__() got an unexpected keyword argument 'lerp'

----------------------------------------------------------------------
Ran 6 tests in 0.018s

FAILED (errors=6)
Macintosh:tests geoff$

**Comment by hpparvi** [comment]
Fixed.
